version: "3"
services:
  postgres:
    image: postgres
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=psql
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres

  back1:
    image: openjdk
    depends_on:
      - postgres
    expose:
      - 8088
    ports:
      - 8081:8088
    volumes:
      - .\build\libs\mpi-backend-1.0-SNAPSHOT.jar:/home/data/back.jar
    command: java -jar /home/data/back.jar
  back2:
    image: openjdk
    depends_on:
      - "postgres"
    expose:
      - 8088
    ports:
      - 8082:8088
    volumes:
      - .\build\libs\mpi-backend-1.0-SNAPSHOT.jar:/home/data/back.jar
    command: java -jar /home/data/back.jar

  haproxy:
    image: haproxy
    depends_on:
      - back1
      - back2
    ports:
      - 80:80
      - 8084:8084
    volumes:
      - .\haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
