server:
  shutdown: graceful
  port: 8088

spring:
  application:
    name: mpi-backend
  datasource:
    url:  jdbc:postgresql://localhost:5432/studs?currentSchema=sXXXXXX
    username: sXXXXX
    password: pswd
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:5432/studs?currentSchema=sXXXXXX
    user: "sXXXXXX"
    password: "pswd"
    default-schema: "sXXXXXX"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always