spring:
  application:
    name: mpi-backend
  profiles:
    active: helios

server:
  shutdown: graceful
  port: 8088

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always