server:
  shutdown: graceful
  port: 8088

spring:
  application:
    name: mpi-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mpi_coursework
    username: mag_db
    password: mag_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always